export const REGISTER_ACCOUNT = "REGISTER_ACCOUNT"
export const REGISTER_ACCOUNT_SUCCESSFUL = "REGISTER_ACCOUNT_SUCCESSFUL"
export const REGISTER_ACCOUNT_FAILED = "REGISTER_ACCOUNT_FAILED"
// export const RESET_REGISTER_FLAG = "RESET_REGISTER_FLAG";

