// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_PORTFOLIO_CHARTS_DATA = "GET_PORTFOLIO_CHARTS_DATA";
export const GET_MARKET_CHARTS_DATA = "GET_MARKET_CHARTS_DATA";
export const FETCH_DEVICE_DATA = 'FETCH_DEVICE_DATA';
export const FETCH_DEVICE_DATA_SUCCESS = 'FETCH_DEVICE_DATA_SUCCESS';
export const FETCH_DEVICE_DATA_FAILURE = 'FETCH_DEVICE_DATA_FAILURE';