export const REGISTER_DEVICE = "REGISTER_DEVICE"
export const REGISTER_DEVICE_SUCCESSFUL = "REGISTER_DEVICE_SUCCESSFUL"
export const REGISTER_DEVICE_FAILED = "REGISTER_DEVICE_FAILED"
// export const RESET_REGISTER_FLAG = "RESET_REGISTER_FLAG";
export const REGISTER_DEVICE_RESET = "REGISTER_DEVICE_RESET"

